MyPicDay/piku-back

src/main/java/store/piku/back/diary/controller/DiaryController.java, src/main/java/store/piku/back/diary/dto/DiaryDTO.java, src/main/java/store/piku/back/diary/dto/DiaryResponse.java, src/main/java/store/piku/back/diary/dto/PhotoDTO.java, src/main/java/store/piku/back/diary/dto/ResponseDTO.java, src/main/java/store/piku/back/diary/entity/Diary.java, src/main/java/store/piku/back/diary/entity/Photo.java, src/main/java/store/piku/back/diary/entity/Status.java, src/main/java/store/piku/back/diary/exception/DiaryNotFoundException.java, src/main/java/store/piku/back/diary/repository/DiaryRepository.java, src/main/java/store/piku/back/diary/repository/PhotoRepository.java, src/main/java/store/piku/back/diary/service/DiaryService.java, src/main/java/store/piku/back/diary/service/LocalPhotoStorage.java, src/main/java/store/piku/back/diary/service/PhotoStorage.java, src/main/java/store/piku/back/diary/service/PhotoUtil.java, src/main/java/store/piku/back/global/error/ErrorCode.java, src/main/java/store/piku/back/global/exception/BusinessException.java
- closed: #5 
- 작업 요약: 
마지막 코드리뷰 후에 " 로그 추가 , 메소드 이름 통일 , Diary 엔티티에 User 연관관계 매핑 후 엔티티에 user_id 확인 " 했습니다 !
=> 일기작성 기능 추가

build.gradle, src/main/java/store/piku/back/ai/controller/AiGeneratorController.java, src/main/java/store/piku/back/auth/controller/AuthController.java, src/main/java/store/piku/back/auth/dto/LoginRequest.java, src/main/java/store/piku/back/auth/dto/SignupRequest.java, src/main/java/store/piku/back/character/controller/CharacterController.java, src/main/java/store/piku/back/diary/controller/DiaryController.java, src/main/java/store/piku/back/global/config/OpenApiConfig.java, src/main/java/store/piku/back/global/config/SecurityConfig.java
=> swagger 추가

src/main/java/store/piku/back/diary/controller/DiaryController.java, src/main/java/store/piku/back/diary/service/DiaryService.java
=> 일기 상세 조회 수정

src/main/java/store/piku/back/diary/controller/DiaryController.java, src/main/java/store/piku/back/diary/service/DiaryService.java
- closed:
- 작업 요약: 아바타 이미지 반환할때 api 제거
=> 아바타 이미지 반환 시 api 제거

src/main/java/store/piku/back/diary/exception/DiaryAcceptException.java
- closed:
- 작업 요약: DiaryAcceptException 패키지 전역 -> diary, comment로 제한
=> DiaryAcceptException 패키지 지정

src/main/java/store/piku/back/friend/controller/FriendRequestController.java, src/main/java/store/piku/back/friend/dto/FriendRequestDto.java, src/main/java/store/piku/back/friend/dto/FriendRequestResponseDto.java, src/main/java/store/piku/back/friend/dto/FriendsDto.java, src/main/java/store/piku/back/friend/entity/Friend.java, src/main/java/store/piku/back/friend/entity/FriendRequest.java, src/main/java/store/piku/back/friend/exception/AlreadyFriendsException.java, src/main/java/store/piku/back/friend/exception/FriendException.java, src/main/java/store/piku/back/friend/exception/FriendRequestNotFoundException.java, src/main/java/store/piku/back/friend/key/FriendID.java, src/main/java/store/piku/back/friend/key/FriendRequestID.java, src/main/java/store/piku/back/friend/repository/FriendRepository.java, src/main/java/store/piku/back/friend/repository/FriendRequestRepository.java, src/main/java/store/piku/back/friend/service/FriendRequestService.java
- closed: #33 
- closed: #28 
- closed : #30 
- 작업 요약:
=> 요청 & 친구목록 조회 & 중복 데이터 방지

src/main/java/store/piku/back/comment/controller/CommentController.java, src/main/java/store/piku/back/comment/dto/CommentRequestDto.java, src/main/java/store/piku/back/comment/entity/Comment.java, src/main/java/store/piku/back/comment/exception/CommentErrorCode.java, src/main/java/store/piku/back/comment/exception/CommentException.java, src/main/java/store/piku/back/comment/exception/CommentExceptionHandler.java, src/main/java/store/piku/back/comment/service/CommentService.java
- closed: #36 
- 작업 요약: 댓글 등록과 대댓글 등록을 하나의 로직으로 병합
- Comment 도메인 예외처리 추가
=> 댓글 등록 & comment 도메인 예외처리 

src/main/java/store/piku/back/diary/controller/DiaryController.java, src/main/java/store/piku/back/diary/dto/DiaryDTO.java, src/main/java/store/piku/back/diary/dto/ResponseDTO.java, src/main/java/store/piku/back/diary/exception/DiaryAcceptException.java, src/main/java/store/piku/back/diary/exception/DuplicateDiaryException.java, src/main/java/store/piku/back/diary/repository/DiaryRepository.java, src/main/java/store/piku/back/diary/service/DiaryService.java, src/main/java/store/piku/back/friend/controller/FriendRequestController.java, src/main/java/store/piku/back/friend/repository/FriendRepository.java, src/main/java/store/piku/back/friend/repository/FriendRequestRepository.java, src/main/java/store/piku/back/friend/service/FriendRequestService.java
=> (수정 )  친구요청 + 일기 등록

src/main/java/store/piku/back/diary/service/DiaryService.java, src/main/java/store/piku/back/friend/controller/FriendRequestController.java, src/main/java/store/piku/back/friend/entity/Friend.java, src/main/java/store/piku/back/friend/repository/FriendRepository.java, src/main/java/store/piku/back/friend/service/FriendRequestService.java
=> 일기 목록 아바타 수정 + 친구조회

src/main/java/store/piku/back/diary/controller/DiaryController.java, src/main/java/store/piku/back/diary/service/DiaryService.java, src/main/java/store/piku/back/file/FileUtil.java
- closed:
- 작업 요약: heic 확장자를 가지는 이미지도 업로드 할 수 있도록 변경
=> 이미지 업로드 확장자 heic 추가

src/main/java/store/piku/back/diary/repository/DiaryRepository.java, src/main/java/store/piku/back/diary/service/DiaryService.java, src/main/java/store/piku/back/friend/repository/FriendRepository.java, src/main/java/store/piku/back/friend/service/FriendRequestService.java, src/main/java/store/piku/back/user/controller/UserController.java, src/main/java/store/piku/back/user/dto/response/ProfilePreviewDTO.java, src/main/java/store/piku/back/user/service/UserProfileService.java
- closed: #57 
- 작업 요약: 프로필 미리보기 기능 추가 (유저id, 닉네임, 아바타, 친구 수, 일기 수, 친구 상태 반환)
=> 프로필 미리보기 조회 기능

src/main/java/store/piku/back/friend/controller/FriendRequestController.java
=> 버그 수정 : 친구 반환 값 변경

src/main/java/store/piku/back/diary/service/DiaryService.java, src/main/java/store/piku/back/global/exception/GlobalExceptionHandler.java
- closed:
- 작업 요약: IOException 처리항목 추가 
Connection reset by peer
An existing connection was forcibly closed
=> IOException

src/main/java/store/piku/back/diary/service/DiaryService.java, src/main/java/store/piku/back/global/exception/GlobalExceptionHandler.java
- closed:
- 작업 요약: validation 에서 NullpointException발생
=> NullpointException

src/main/java/store/piku/back/ai/repository/DiaryImageGenerationRepository.java, src/main/java/store/piku/back/diary/controller/DiaryController.java, src/main/java/store/piku/back/diary/dto/DiaryDTO.java, src/main/java/store/piku/back/diary/dto/DiaryImageInfo.java, src/main/java/store/piku/back/diary/entity/Photo.java, src/main/java/store/piku/back/diary/service/DiaryService.java, src/main/java/store/piku/back/diary/service/LocalPhotoStorage.java, src/main/java/store/piku/back/diary/service/PhotoStorage.java, src/main/java/store/piku/back/global/exception/GlobalExceptionHandler.java
- closed:
- 작업 요약: 일기 사진을 순서대로 저장하기 위해 일기 등록 부분이 수정되었습니다
=> 일기 사진 순서로 인해 등록 변경

src/main/java/store/piku/back/global/config/SecurityConfig.java
- closed:
- 작업 요약: 댓글 수정 등 수정작업을 위해 설정에 추가합니다
=> Http Method PATCH 추가

.github/workflows/ci-cd-prod.yml
=> ci-cd-prod.yml 생성

src/main/java/store/piku/back/global/config/SecurityConfig.java
=> CORS 설정 추가

src/main/java/store/piku/back/auth/constants/AuthConstants.java, src/main/java/store/piku/back/auth/controller/AuthController.java, src/main/java/store/piku/back/auth/dto/request/EmailValidRequest.java, src/main/java/store/piku/back/auth/dto/request/PwdResetRequest.java, src/main/java/store/piku/back/auth/entity/VerifiedEmail.java, src/main/java/store/piku/back/auth/exception/AuthErrorCode.java, src/main/java/store/piku/back/auth/repository/VerifiedEmailRepository.java, src/main/java/store/piku/back/auth/service/AuthService.java
- closed: #119 
- 작업 요약 : 이메일 인증 후 회원가입 및 비밀번호 찾기 가능하도록 강제
=> 이메일 인증 후 회원가입 및 비밀번호 찾기

src/main/java/store/piku/back/auth/constants/EmailConstants.java, src/main/java/store/piku/back/auth/service/EmailService.java, src/main/java/store/piku/back/global/notification/DiscordWebhookService.java, src/main/java/store/piku/back/inquiry/controller/InquiryController.java, src/main/java/store/piku/back/inquiry/entity/Inquiry.java, src/main/java/store/piku/back/inquiry/service/InquiryService.java
- closed:
- 작업 요약: 
- 글자 수 제한을 추가했습니다
- 피드백 작성 시 관리자의 이메일로 피드백 내용이 전달됩니다
=> 피드백 제약조건 및 관리자 이메일로 발송 추가

.github/workflows/ci-cd-prod.yml
=> 프론트 ci/cd 제거

allowedemail.sql, src/main/java/store/piku/back/ai/controller/AiGeneratorController.java, src/main/java/store/piku/back/ai/dto/AiDiaryResponseDTO.java, src/main/java/store/piku/back/ai/service/ImageGenerationService.java, src/main/java/store/piku/back/auth/controller/AuthController.java, src/main/java/store/piku/back/auth/dto/request/SignupRequest.java, src/main/java/store/piku/back/auth/entity/AllowedEmail.java, src/main/java/store/piku/back/auth/exception/AuthErrorCode.java, src/main/java/store/piku/back/auth/repository/AllowedEmailDomainRepository.java, src/main/java/store/piku/back/auth/service/AuthService.java, src/main/java/store/piku/back/auth/service/EmailService.java
=> 허용 이메일 도메인 추가

src/main/java/store/piku/back/diary/controller/DiaryController.java, src/main/java/store/piku/back/diary/dto/ResponseDTO.java, src/main/java/store/piku/back/diary/service/DiaryService.java, src/main/java/store/piku/back/diary/service/FeedService.java
- closed: #130 
- 작업 요약: 일기 조회 시 댓글 개수 포함하여 반환
=> 일기 조회 시 댓글 개수 포함하여 반환
